version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

