version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "62765:80"

  redis:
    ports:
      - "6379:6379"

  mariaDb:
    volumes:
      - ./MySql/data:/var/lib/mysql
      - ./MySql/initdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chat
      - MYSQL_USER=chat_user
      - MARIADB_PASSWORD=chat_password
    ports:
      - "3306:3306"